name: ğŸ¤– [PUBLISH] Package ğŸ“¦ 

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  build-main:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ— Checkout main branch 
        uses: actions/checkout@v3
      - name: ğŸ”§ Configure git
        run: | 
          git config --global user.email "devops+bot2022@muuvlabs.com"
          git config --global user.name "ğŸ¤– DEVOPS-B0T-2022"
      - name: â˜• Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: ğŸ“¦ Install dependencies 
        run: npm i 
      - name: ğŸ­ Build Project
        run: npm run build
      - name: ğŸ“¦ Publish  
        run: |
          npm config set //npm.pkg.github.com/@knerd:_authToken ${NPM_TOKEN}
          npm publish --ignore-scripts
        env:
          GITHUB_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
