name: ü§ñ [FF] develop branch ‚è© 
on:
  push:
    branches: 
      - main 
  workflow_dispatch:
    
jobs:
  fast-forward-develop:
    runs-on: ubuntu-latest
    steps:
    - name: üèó Checkout main
      uses: actions/checkout@v1
    - name: ‚è© Fast Forward develop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/knerd/github-actions
        git config --global user.email "devops+bot2022@muuvlabs.com"
        git config --global user.name "ü§ñ DEVOPS-B0T-2022"
        git fetch origin develop 
        git checkout develop
        git merge origin/main --ff-only
        git push origin develop 