name: ðŸ“£ Announce Release

on:
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  workflow: 
    uses: ./.github/workflows/build.yml
    
  release-tag:
    needs: workflow
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“‘ Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ðŸ“£ Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}
