name: ðŸ“£ Announce Release

on:
  workflow_call:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: " ðŸ“‘ Refresh tags"
        id: tag
        run: |
          git fetch --tags --force # Is currently required for v3 due to https://github.com/actions/checkout/issues/290
          git checkout v$(node -p "require('./package.json').version")
      - uses: ericcornelissen/git-tag-annotation-action@v2
        id: tag-data
      - name:  ðŸ“£ Create GitHub release
        uses: Roang-zero1/github-create-release-action@v2
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          release_text: ${{ steps.tag-data.outputs.git-tag-annotation }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
