name: ðŸ†• Changelog CI

on:
  pull_request:
    types: [ opened ]

jobs:
  log-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: ðŸ†• Run Changelog CI
        uses: saadmk11/changelog-ci@v1.0.0