name: ğŸ¤–ğŸš€ Deploy Production ğŸ¬

on:
  workflow_call:
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  URL: "https://www.example.com"

jobs:
  deploy-prod:
    environment:
      name: PRODUCTION 
      url: ${{ env.URL }} 
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout main branch 
        uses: actions/checkout@v3
      - name: ğŸ” Connect to environement 
        run: |
          echo "Connect to Production server"
      - name: ğŸš€ Deploy latest code 
        run: |
          echo "Run deployment code..."
