name: ğŸ¤–ğŸš€ Deploy Production ğŸ¬

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy-prod:
    environment:
      name: prod
      url: "https://www.example.com"
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout main branch 
        uses: actions/checkout@v3
      - name: ğŸ” Connect to environement 
        run: |
          echo "Connect to Production / Staging server"
      - name: ğŸš€ Deploy latest code 
        run: |
          echo "Run deployment code..."
