name: ğŸš€ Deploy Production ğŸ¬

on:
  workflow_call:
  workflow_dispatch:

jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ— Checkout main branch 
        uses: actions/checkout@v3
      - name: â˜• Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@majora-d"
      - name: ğŸ“¦ Install dependencies 
        run: npm ci 
      - name: ğŸ­ Build Project
        run: npm run build
      - name: ğŸ“¦ Publish  
        run: npm publish 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
