name: ğŸ¤–ğŸš€ Deploy Staging ğŸ§ª 

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - develop

# Environment variables available to all jobs and steps in this workflow
env:
  URL: "https://staging.example.com"

jobs:
  deploy-staging:
    environment:
      name: STAGING 
      url: ${{ env.URL }} 
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout main branch 
        uses: actions/checkout@v3
      - name: ğŸ” Connect to environement 
        run: |
          echo "Connect to Staging server"
      - name: ğŸš€ Deploy latest code 
        run: |
          echo "Run deployment code..."
