name: üëÜ‚ô®Ô∏è Dispatch hotfix branch

on:
  push:
    branches:
      - hotfix 
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  USER_EMAIL: "bot+202X@myorg.com"
  USER_NAME: "ü§ñ workflows[bot]2022"
  # GITHUB_TOKEN: ${{ secrets.GH_PA_TOKEN }}
  # To disable the pull_request from triggering your other workflows, use GITHUB_TOKEN instead
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  dispatch-branch:
    runs-on: ubuntu-latest
    steps:
      - name: üèó Check out develop branch 
        uses: actions/checkout@v3
        with:
          ref: $default-branch
      - name: üîß Configure git
        run: | 
          git config --global user.email ${{ env.USER_EMAIL }}
          git config --global user.name "${{ env.USER_NAME }}" 
      - name: üîñ Bump version 
        id: bump 
        run: |
          npm version patch
          VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=HOTFIX::hotfix/$VERSION" 
      - name: ‚ô®Ô∏è Create hotfix branch 
        run: |
          HOTFIX=${{ steps.bump.outputs.HOTFIX }}
          git checkout -b $HOTFIX
          git push -u origin $HOTFIX
      - name: üßê Submit pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.bump.outputs.HOTFIX }}
          destination_branch: $default-branch
          pr_label: "hotfix"
          pr_title: "${{ steps.bump.outputs.HOTFIX }} ‚ô®Ô∏è"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"  
          github_token: ${{ env.GITHUB_TOKEN }} 