name: ğŸ‘† [PR] Next Increment ğŸ”– 

on:
  workflow_dispatch:

jobs:
  next-increment:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Check out develop branch 
        uses: actions/checkout@v3
        with:
          ref: 'develop'
      - uses: ./.github/workflows/build.yml
      - name: ğŸ”§ Configure git
        run: | 
          git config --global user.email "devops+bot2022@muuvlabs.com"
          git config --global user.name "ğŸ¤– DEVOPS-B0T-2022"
      - name: ğŸ”– Bump version 
        id: bump 
        run: |
          echo "::set-output name=RELEASE::release/$(npm version minor)" 
      - name: ğŸ“¦ Create release branch 
        run: |
          RELEASE=${{ steps.bump.outputs.RELEASE }}
          git checkout -b $RELEASE
          git push -u origin $RELEASE
      - name: ğŸ§ Submit pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.bump.outputs.RELEASE }}
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automated pr, release"
          pr_title: "ğŸ”– ${{ steps.bump.outputs.RELEASE }} "
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"  