name: ğŸ‘†ğŸš‘ Dispatch hotfix branch

on:
  workflow_dispatch:

jobs:
  dispatch-branch:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Check out develop branch 
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: ğŸ”§ Configure git
        run: | 
          git config --global user.email "devops+bot@muuvlabs.com"
          git config --global user.name "ğŸ¤– hotfix[bot]2022"
      - name: ğŸ”– Bump version 
        id: bump 
        run: |
          npm version patch
          VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=HOTFIX::hotfix/$VERSION" 
      - name: ğŸš‘ Create hotfix branch 
        run: |
          HOTFIX=${{ steps.bump.outputs.HOTFIX }}
          git checkout -b $HOTFIX
          git push -u origin $HOTFIX
      - name: ğŸ§ Submit pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ steps.bump.outputs.HOTFIX }}
          destination_branch: "main"
          pr_label: "hotfix"
          pr_title: "${{ steps.bump.outputs.HOTFIX }} ğŸš‘"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"  
          github_token: ${{ secrets.GH_PA_TOKEN }}
          # To disable the pull_request from triggering your other workflows, use GITHUB_TOKEN instead
          # github_token: ${{ secrets.GITHUB_TOKEN }}