name: _ğŸ‘†ğŸ”– Dispatch next minor release 

on:
  workflow_dispatch:
  # schedule:
  #   # At 00:00 every Tuesday
  #   - cron: '0 0 * * TUE'

jobs:
  dispatch-branch:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ‘†ğŸ”– Dispatch Next Minor Release w/ PR
        uses: knerd/pr-next-minor-release-action@v1