name: ğŸ‘† [PR] Hotfix ğŸš‘ 

on:
  workflow_dispatch:

jobs:
  dispatch-hotfix-branch:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Check out develop branch 
        uses: actions/checkout@v3
        with:
          ref: 'main'
      - name: ğŸ­ Build
      - uses: ./.github/workflows/build
      - name: ğŸ”§ Configure git
        run: | 
          git config --global user.email "devops+bot2022@muuvlabs.com"
          git config --global user.name "ğŸ¤– DEVOPS-B0T-2022"
      - name: ğŸ”– Bump version 
        id: bump 
        run: |
          echo "::set-output name=VERSION::$(npm version patch)" 
      - name: ğŸš‘ Create hotfix branch 
        run: |
          BRANCH=hotfix/${{ steps.bump.outputs.VERSION }}
          git checkout -b $BRANCH
          git push -u origin $BRANCH
      - name: ğŸ§ Submit pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: hotfix/${{ steps.bump.outputs.VERSION }}
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automated pr, hotfix"
          pr_title: " ğŸ”– ${{ steps.bump.outputs.VERSION }} ğŸš‘"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"  