name: ğŸ“¦ [PR]  Release Product Increment 

on:
  workflow_dispatch:

jobs:
  package-release:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Check out develop branch 
        uses: actions/checkout@v3
        with:
          ref: 'develop'
      - name: ğŸ”§ Configure git
        run: | 
          git config --global user.email "devops+bot2022@muuvlabs.com"
          git config --global user.name "ğŸ¤– DEVOPS-B0T-2022"
      - name: ğŸ”– Bump version 
        id: bump 
        run: |
          echo "::set-output name=VERSION::$(npm version minor)" 
      - name: ğŸ“¦ Create release branch 
        run: |
          git checkout -b release/${{ steps.bump.outputs.VERSION }}
          git push -u origin release/${{ steps.bump.outputs.VERSION }}
          git push --tags
      - name: ğŸ§ Submit pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: release/${{ steps.bump.outputs.VERSION }}
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automated pr, release"
          pr_title: "ğŸ”– ${{ steps.bump.outputs.VERSION }}"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"  