name: ğŸ“¦ [PR] Release Package 

on:
  workflow_dispatch:

jobs:
  package-release:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Check out repository code
        uses: actions/checkout@v3
        with:
          ref: 'develop'
      - name: ğŸ“¦ 'cat package.json'
        run: cat ./package.json
      - name: ğŸ”§ Configure git
        run: | 
          git config --global user.email "devops+bot2022@muuvlabs.com"
          git config --global user.name "ğŸ¤– DEVOPS-B0T-2022"
      - name: ğŸ”– 'npm version minor'
        id: bump 
        run: |
          VERSION=$(npm version minor)
          echo $VERSION
          git push
          git push --tags
          echo '::set-output name=VERSION::$VERSION'
      - name: Output
      - name: ğŸ“¦ 'cat package.json'
        run: cat ./package.json
      - name: ğŸ¤– Create pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automated pr, release"
          pr_title: "ğŸ“¦ Merge ğŸ”– ${{ steps.bump.outputs.VERSION }} into main"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body