name: ðŸ¤–ðŸ“¦ Publish Release 

on:
  workflow_call:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ— Checkout main branch 
        uses: actions/checkout@v3
      - name: â˜• Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: "@knerd"
      - name: ðŸ“¦ Install dependencies 
        run: npm ci 
      - name: ðŸ­ Build Project
        run: |
          echo '//npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}' >> .npmrc
          npm run build
      - name: ðŸ“¦ Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          registry: https://npm.pkg.github.com/
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
