name: ğŸ“¦ Package Release PR

on:
  workflow_dispatch:

jobs:
  package-release:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Check out repository code
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name: ğŸ“¦ 'cat package.json'
        run: cat ./package.json
      - name: ğŸ”§ Configure git
        run: | 
          git config --global user.email "bot@muuvlabs.com"
          git config --global user.name "ğŸ¤–DevOpsBot"
      - name: ğŸ”– 'npm version minor'
        id: bump 
        run: |
          VERSION=$(npm version minor)
          echo $VERSION
          git push
          git push --tags
          echo '::set-output name=VERSION::$VERSION'
      - name: Set selected color
        run: echo '::set-output name=SELECTED_COLOR::green'
      - name: Get color
        run: echo "The selected color is "
      - name: ğŸ“¦ 'cat package.json'
        run: cat ./package.json
      - name: ğŸ¤– Create pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automated pr, feature/fix"
          pr_title: "ğŸ“¦ Merge ğŸ”– ${{ steps.bump.outputs.VERSION }} into main"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body