name:  Auto bump version and create release PR from develop

on:
  workflow_dispatch:

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name:  Check out repository code
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name:  'cat package.json'
        run: cat ./package.json
      - name:  'npm version minor'
        id: version-bump
        run: npm version minor 
      - name:  'cat package.json'
        run: cat ./package.json
      - name:  Create pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_label: "automated pr, feature/fix"
          pr_title: " Merge Develop into Release"
          pr_template: ".github/PULL_REQUEST_TEMPLATE.md"   # Path to pull request template, requires pr_title to be set, excludes pr_body