name:  Auto bump version and create release PR from develop

on:
  push:
    tags:
      - '*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name:  Check out repository code
        uses: actions/checkout@v2
        with:
          ref: 'develop'
      - name:  'cat package.json'
        run: cat ./package.json
      - name:  'npm version minor'
        id: version-bump
        run: npm version minor 
      - name:  'cat package.json'
        run: cat ./package.json
      - name:  Create pull request
        id: pr
        uses: repo-sync/pull-request@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
