name: ğŸ¤– [TAG] Publish Releast ğŸ“¦ 

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  workflow: 
    uses: ./.github/workflows/build.yml
    
  release-tag:
    needs: workflow
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“‘ Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: ğŸ”– Create Release
        uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
        with:
          body: ${{steps.github_release.outputs.changelog}}
      - name: ğŸ“¦ Install dependencies 
        run: npm ci 
      - name: ğŸ­ Build Project
        run: npm run build
      - name: ğŸ“¦ Publish  
        run: npm publish 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-package:
    uses: ./.github/workflows/publish.yml
