name: ğŸ¤–ğŸ”– Tag > ğŸ“£ Release > â© Sync > ğŸ“¦Publish > ğŸš€ Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Environment variables available to all jobs and steps in this workflow
env:
  USER_EMAIL: "bot+202X@myorg.com"
  USER_NAME: "ğŸ¤– workflows[bot]2022"
  GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout main branch 
        uses: actions/checkout@v3

      - name: ğŸ”§ Configure git
        run: | 
          git config --global user.email ${{ env.USER_EMAIL }}
          git config --global user.name "${{ env.USER_NAME }}" 

      - name: ğŸ”– Tag 
        run: |
          git tag v$(node -p "require('./package.json').version")
          git push --tags 

  announce-release: 
    needs: tag
    uses: ./.github/workflows/announce-release.yml
    secrets: inherit

  sync-dev: 
    needs: announce-release 
    uses: ./.github/workflows/synchronize-develop.yml
    secrets: inherit

  publish: 
    needs: announce-release 
    uses: ./.github/workflows/publish.yml
    secrets: inherit

  deploy: 
    needs: publish 
    uses: ./.github/workflows/deploy-prod.yml
    secrets: inherit