name: ğŸ”– Tag main 

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ— Checkout main branch 
        uses: actions/checkout@v3
        env: 
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ğŸ”§ Configure git
        run: | 
          git config --global user.email "devops+bot2022@muuvlabs.com"
          git config --global user.name "ğŸ¤– workflows[bot]2022"
        env: 
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: ğŸ”– Tag 
        run: |
          git tag v$(node -p "require('./package.json').version")
          git push --tags 
        env: 
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}

  announce-release: 
    needs: tag
    uses: ./.github/workflows/announce-release.yml

  publish: 
    uses: ./.github/workflows/publish.yml

  deploy: 
    needs: announce-release 
    uses: ./.github/workflows/deploy.yml
